### ISSUE TITLE
Write the abstract for kozilly to University

### ISSUE THREAD

**Issue by smpiano** [kozily/admin#162]

**Comment by smpiano** [comment]
En 5 lineas

``Los alumnos Andrés Gastón Arana y Sergio Matías Piano presentarán Kozily, una máquina virtual y entorno de desarrollo para el lenguaje Oz con fines educativos. La herramienta de desarrollo está disponible a través de una interfaz web para que cualquiera pueda acceder, utilizarla y aprender con ella, bajo la dirección de la licenciada Rosita Wachenchauzer y el Ingeniero Leandro Ferrigno.``

**Comment by andres-arana** [comment]
Se lo mandé a Leandro para que lo revise.
