### ISSUE TITLE
Built-in number operations

### ISSUE THREAD

**Issue by andres-arana** [kozily/admin#84]
Implemen the kernel for the following number built-ins:

* ```{Number.'+' X Y Z}```
* ```{Number.'-' X Y Z}```
* ```{Number.'*' X Y Z}```
* ```{Number.'div' X Y Z}```
* ```{Number.'mod' X Y Z}```
* ```{Float.'/' X Y Z}```

**Comment by smpiano** [comment]
Extended syntax was moved to issue https://github.com/kozily/admin/issues/134
